name: kalm
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - einops
    - typed-argument-parser
    - tqdm
    - matplotlib
    - scipy
    - tensorboard
    - opencv-python
    - open3d
    - trimesh
    - openai
    - seaborn
    - pyglet<2
    - diffusers[torch]
    - git+https://github.com/facebookresearch/segment-anything.git
    - pybullet
