name: kalm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - git+https://github.com/openai/CLIP.git
    - numpy
    - pillow
    - einops
    - typed-argument-parser
    - tqdm
    - transformers
    - absl-py
    - matplotlib
    - scipy
    - tensorboard
    - opencv-python
    - blosc
    - setuptools==57.5.0
    - beautifulsoup4
    - bleach>=6.0.0
    - defusedxml
    - jinja2>=3.0
    - jupyter-core>=4.7
    - jupyterlab-pygments
    - mistune==2.0.5
    - nbclient>=0.5.0
    - nbformat>=5.7
    - pandocfilters>=1.4.1
    - tinycss2
    - traitlets>=5.1
    - pandas
    - scikit-learn
    - open3d
    - pydantic
    - pyrep
    - trimesh
    - openai
    - seaborn
    - pyglet<2
    - diffusers[torch]
    - git+https://github.com/facebookresearch/segment-anything.git
    - yourdfpy
    - pybullet
